apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nodejs-template
  description: Standard nodejs Service.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest